app_name: "FoodMarket"
app_port: 1233

db_host:
db_port:
db_user: ""
db_pass: ""
db_name: ""
db_ssl_mode: ""

jwt_secret: ""
JWT_EXPIRED_TOKEN_DURATION: 10000
mail_sender: "mail@foodmarket.io"
mail_host: "smtp.mailtrap.io"
mail_port: 2525
mail_username: ""
mail_password: ""
mail_encrypt: tls

midtrans_server_key: ""
midtrans_client_key: ""

MINIO_KEY: ""
MINIO_SECRET: ""
MINIO_ENDPOINT: ""
MINIO_BUCKET: ""
MINIO_REGION: ""
MINIO_CDN: ""
MINIO_SSL: ""