app_name: "FoodMarket"
app_port: 1233

db_host: 127.0.0.1
db_port: 5432
db_user: "postgres"
db_pass: "default"
db_name: "foodmarket"
db_ssl_mode: "disable"

JWT_EXPIRED_TOKEN_DURATION: "1000"
jwt_secret: "FoodMarket123456"