version: '3.5'
services:
  foodmarket-api:
    image: golang:alpine
    working_dir: /usr/src/app/
    command: sh -c "go run ."
    container_name: foodmarket-api
    ports: 
      - 1233:1233 
    restart: on-failure
    volumes:
      - .:/usr/src/app/
    depends_on:
      - foodmarket-db        # Uncomment this when using postgres.
    networks:
      - fullstack

  foodmarket-db:
    image: 'postgres:alpine'
    container_name: foodmarket-db
    hostname: foodmarket-db
    environment:
      - POSTGRES_USER=userfoodmarketdb
      - POSTGRES_PASSWORD=foodmarketdb123
      - POSTGRES_DB=foodmarketdb
    restart: always
    ports:
      - "21543:5432"
    volumes:
      - ./infra/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - fullstack
  
  foodmarket-pgadmin:
    container_name: foodmarket-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - /infra/data/pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5051}:80"
    networks:
      - fullstack
    depends_on:
      - foodmarket-db  
    restart: unless-stopped

volumes:
  foodmarket-api:
  foodmarket-db: 
     
networks:
  fullstack:
    driver: bridge